### ISSUE TITLE
Enlaces

### ISSUE THREAD

**Issue by Makova** [renatolrr/OpenDataDay2015#1]
A la wiki sobre Scraping, al tuto que hizó Sera. No sé parece que podría llevar más enlaces, queda bien y si alguién lo descarga eso que se lleva :+1:

**Comment by Makova** [comment]
Te he forkeado el repo y cambiado algunas cosillas, luego lo ves.

**Comment by renatolrr** [comment]
Ya lo he resuelto, muchísimas gracias.
